insert into paciente(ID_PACIENTE,NOME,CPF,SEXO,RG) VALUES(1,'FULANO PACIENTE','321354314','M',132);
insert into proprietario(ID,NOME,CPF,SEXO,RG) VALUES(1,'FULANO PROPRIETARIO','315438979','M',4156);
insert into recepcionista(ID,NOME,CPF,SEXO,PROPRIETARIO_ID,RG) VALUES(1,'FULANA RECEPCIONISTA','321354314','F',1,123);
insert into medico(ID,NOME,CPF,SEXO,PROPRIETARIO_ID,RG) VALUES(1,'FULANO MEDICO','321354314','M',1,456);
insert into consulta(ID,ALTURA,DESCRICAO,MEDICO_ID,RECEPCIONISTAS_ID, PACIENTE_ID_PACIENTE) VALUES(1,1.70,'TALTAL CONSULTA',1,1,1);
insert into RECEPCIONISTA_PACIENTES(RECEPCIONISTAS_ID,PACIENTES_ID_PACIENTE) VALUES(1,1);